/*
This script was generated by TablePlus. It only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.
*/

-- Sequence
CREATE SEQUENCE IF NOT EXISTS "public"."podcasts_id_seq";

-- Table Definition
CREATE TABLE "public"."podcasts" (
    "id" int4 DEFAULT nextval('podcasts_id_seq'::regclass),
    "title" varchar(255),
    "description" text,
    "file_mp3" varchar(255),
    "file_ogg" varchar(255),
    "created_at" timestamp,
    "updated_at" timestamp,
    PRIMARY KEY ("id")
);